### ISSUE TITLE
支持机器远程绑定端口进行调试 即让其他非本地ip的机子支持ip+：+端口号的绑定

### ISSUE THREAD

**Issue by bakso** [AlloyTeam/Rythem#40]
fiddler支持这个功能，但是默认关闭，在options里的某一个选项卡里可以找到

**Comment by iptton** [comment]
这个功能已经实现的了，只需把绑定监听的ip地址改一下就行了 https://github.com/iptton/Rythem 这个分支上已经实现，正在进行Qt5改造，由于时间的关系进度比较慢

**Comment by zhaoda** [comment]
@iptton 请问这个功能有release版本么？

**Comment by iptton** [comment]
@zhaoda https://github.com/AlloyTeam/Rythem/releases/tag/Rythem_for_mac_remote_listen 可到此链接下载mac版

**Comment by zhaoda** [comment]
@iptton 谢谢
