### ISSUE TITLE
Rule配置支持通配符的语法

### ISSUE THREAD

**Issue by code4craft** [AlloyTeam/Rythem#43]
看到介绍"匹配模式包括`wildcard`类型及全匹配两种"，但是没有找到相关通配符使用的说明，能说明一下通配符的语法？

**Comment by iptton** [comment]
示例：  
regex:_.yourdomain.com/cgi-bin/get_info_  
可匹配youdomain.com/cgi-bin/get_info?wefsdf=32fwef 之类的请求

具体wildcard语法可以参考此文：http://www.dbgtech.net/windbghelp/hh/debugger/r13_syntax_c980a67c-f2d7-495d-8675-2763584a1516.xml.htm

需要说明的是：之前中间有一版本用的不是wildcard而是正则表达式。

**Comment by code4craft** [comment]
多谢！配置了一下，可以用了。之前尝试过*的格式，要加上regex:前缀倒是没有想到。

**Comment by KiritoStudio** [comment]
请问一下,wildcard语法有没有除外之类的语法?

**Comment by iptton** [comment]
@knightluffy 应该没有吧，请参考我上面给的链接或google一下。
不过没专门学习过wildcard语法，或者是有的，只是我不知道而已。
