### ISSUE TITLE
能否允许用户自行定义监听 IP

### ISSUE THREAD

**Issue by asbai** [AlloyTeam/Rythem#46]
如题，Rythem 很好用，但是有时我们想要查看 Web Service 与外部设备（比如：iPad）之间的通信，这样仅监听 127.0.0.1 就不好用了。

**Comment by iptton** [comment]
新版本已经可以监听外部请求了，可到release界面下载试用

**Comment by asbai** [comment]
是 2013-11-15 咩？木有找到在哪里改的说？

**Comment by iptton** [comment]
不需要修改，没有“设置监听某个ip的功能”。而是增加了监听所有指向本机（不管是本机发起的还是其它设备发起的）的请求。
https://github.com/AlloyTeam/Rythem/releases

**Comment by asbai** [comment]
ok，看到了，多谢！~
![01](https://f.cloud.github.com/assets/5937547/1725530/5f7ac466-6281-11e3-85c2-09e93d88960d.png)
