### ISSUE TITLE
作者，你好 请问  我需要对这个进行二次开发  请问 windows下开发环境如何搭建呢

### ISSUE THREAD

**Issue by xiaolongyuan** [AlloyTeam/Rythem#47]
附上需要解决的问题的帖子 http://www.oschina.net/question/557892_137061 ，谢谢

**Comment by iptton** [comment]
Qt 环境搭配及开发问题，可到 http://qt-project.org/ 或各大编程论坛讨论。这个项目的wiki也有关于本项目的代码阅读相关内容可查阅。
