### ISSUE TITLE
QT4.8.5 环境下运行  大量报错

### ISSUE THREAD

**Issue by xiaolongyuan** [AlloyTeam/Rythem#48]
D:\Workspaces\QT 4.8.5\Rythem-master\rule\ryruleproject.cpp:157: error: C3083: “{ctor}”:“::”左侧的符号必须是一种类型

D:\Workspaces\QT 4.8.5\Rythem-master\proxy\rywinhttp.h:35: error: C2371: “INTERNET_PER_CONN_OPTIONA”: 重定义；不同的基类型

等等

**Comment by xiaolongyuan** [comment]
d:\Workspaces\QT 4.8.5\Rythem-master\Rythem.pro:109: warning: Unescaped backslashes are deprecated.

请问  win32:LIBS += D:\QtSDK\mingw\lib\libwininet.a  这里是不是要改？

**Comment by iptton** [comment]
是的，要改成你本机的mingw目录

**Comment by xiaolongyuan** [comment]
mingw 这个我没装诶  我装的是vs2012的那个版本 请问要怎么改呢？

**Comment by iptton** [comment]
没用vs开发过，帮不了你了。建议你搜索下vs怎么使用 wininet

**Comment by xiaolongyuan** [comment]
我也没用那个  只是我找不到 mingw 

你看我的SDK：

 C:\DevelopTools\QT\4.8.5 的目录

2013/12/16 周一  17:04    <DIR>          .
2013/12/16 周一  17:04    <DIR>          ..
2013/06/07 周五  13:17            29,945 .LICENSE-ALLOS
2013/06/07 周五  13:17            31,462 .LICENSE-ALLOS-US
2013/06/07 周五  13:17            28,473 .LICENSE-DESKTOP
2013/06/07 周五  13:17            30,054 .LICENSE-DESKTOP-US
2013/06/07 周五  13:17            26,968 .LICENSE-EMBEDDED
2013/06/07 周五  13:17            27,693 .LICENSE-EMBEDDED-US
2013/06/07 周五  13:17            15,397 .LICENSE-EVALUATION
2013/06/07 周五  13:17            17,022 .LICENSE-EVALUATION-US
2013/12/16 周一  16:50             1,019 .qmake.cache
2013/06/07 周五  13:16               120 .tag
2013/12/16 周一  21:45    <DIR>          bin
2013/06/27 周四  15:53               145 build-number.txt
2013/06/27 周四  15:19            22,870 changes-4.8.5
2013/12/16 周一  14:11    <DIR>          config.profiles
2013/12/16 周一  14:11    <DIR>          config.tests
2013/06/07 周五  13:16           326,617 configure
2013/12/16 周一  16:50               259 configure.cache
2013/06/07 周五  13:16         1,460,224 configure.exe
2013/12/16 周一  17:04    <DIR>          demos
2013/12/16 周一  14:12    <DIR>          doc
2013/12/16 周一  17:04    <DIR>          examples
2013/12/16 周一  14:11    <DIR>          imports
2013/12/16 周一  14:11    <DIR>          include
2013/06/07 周五  13:17               709 INSTALL
2013/06/07 周五  13:17             1,209 LGPL_EXCEPTION.txt
2013/12/16 周一  22:22    <DIR>          lib
2013/06/07 周五  13:17            26,940 LICENSE
2013/06/07 周五  13:17            23,411 LICENSE.FDL
2013/06/07 周五  13:17            36,934 LICENSE.GPL3
2013/06/07 周五  13:17            26,940 LICENSE.LGPL
2013/12/16 周一  17:04           157,883 Makefile
2013/12/16 周一  16:50    <DIR>          mkspecs
2013/12/16 周一  14:11    <DIR>          plugins
2013/06/07 周五  13:17             7,246 projects.pro
2013/12/16 周一  16:58           433,429 projects.sln
2013/12/16 周一  16:52    <DIR>          qmake
2013/12/16 周一  14:22                46 Qt OpenSource.url

**Comment by xiaolongyuan** [comment]
C:\DevelopTools\QT\4.8.5 的目录

[.]                      [..]                     .LICENSE-ALLOS
.LICENSE-ALLOS-US        .LICENSE-DESKTOP         .LICENSE-DESKTOP-US
.LICENSE-EMBEDDED        .LICENSE-EMBEDDED-US     .LICENSE-EVALUATION
.LICENSE-EVALUATION-US   .qmake.cache             .tag
[bin]                    build-number.txt         changes-4.8.5
[config.profiles]        [config.tests]           configure
configure.cache          configure.exe            [demos]
[doc]                    [examples]               [imports]
[include]                INSTALL                  LGPL_EXCEPTION.txt
[lib]                    LICENSE                  LICENSE.FDL
LICENSE.GPL3             LICENSE.LGPL             Makefile
[mkspecs]                [plugins]                projects.pro
projects.sln             [qmake]                  Qt OpenSource.url
README                   [src]                    [tmp]
[tools]                  [translations]           uninst.exe
[util]
              27 个文件      3,420,301 字节
              19 个目录 62,506,803,200 可用字节

**Comment by xiaolongyuan** [comment]
我用的 官方工具  Qt creator

**Comment by iptton** [comment]
下载一个吧

**Comment by iptton** [comment]
我用的是mingw版本 http://qt-project.org/downloads 
非mingw版本，请自行google找到如何使用 wininet.dll 或 wininet.lib 吧。
