### ISSUE TITLE
windows环境下时间长了会自动退出

### ISSUE THREAD

**Issue by shark2202** [AlloyTeam/Rythem#51]
我是windows环境，这个软件时间长了会自动退出，并且不会修改LAN的代理设置，保持为127.0.0.1端口8889,造成浏览器无法访问网络，提示ERR_PROXY_CONNECTION_FAILD。

**Comment by iptton** [comment]
长时间运行会导致内存使用过高而crash，这个几乎无解（每条请求都会保存下来，而系统分配的空间有限)。有个版本可以限定最高条目的，可以试一下

**Comment by oscarqht** [comment]
@iptton 可以只保留最後比如說100條來限制內存使用量？

**Comment by iptton** [comment]
@moscartong 新版本是支持设置保留最后n条的。
